[project]
name = "escrow"
space = 30000
out_dir = "./target"
provider = "localnet"

[providers.localnet]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"
loader = "6ZjLk7jSFVVb2rxeoRf4ex3Q7zECi5SRTV4HbX55nNdP"

[providers.testnet]
cluster = "testnet"
wallet = "~/.config/solana/id.json"
loader = "6ZjLk7jSFVVb2rxeoRf4ex3Q7zECi5SRTV4HbX55nNdP"

[test]
test_provider = "localnet"
script = "npm run mocha -t 1000000 tests/**/*.ts"
