[project]
name = "escrow"
space = 30000
cache_space = 300000
out_dir = "./target"
provider = "localnet"

[providers.localnet]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"
loader_id = "6ZjLk7jSFVVb2rxeoRf4ex3Q7zECi5SRTV4HbX55nNdP"

[providers.testnet]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"
loader_id = "6ZjLk7jSFVVb2rxeoRf4ex3Q7zECi5SRTV4HbX55nNdP"

[test]
script = "npx mocha -t 1000000 tests/**/*.ts"
