[project]
name = "escrow"
space = 30000
cache_space = 300000
out_dir = "./target"
provider = "localnet"

[providers.localnet]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"
loader_id = "HE7R2wfjpgjHnxfA9bS6fSLJzm7nucFfBXQhhxTCWMZs"

[providers.testnet]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"
loader_id = "HE7R2wfjpgjHnxfA9bS6fSLJzm7nucFfBXQhhxTCWMZs"

[test]
script = "npx mocha -t 1000000 tests/**/*.ts"
